### ISSUE TITLE
plain-text http2?!

### ISSUE THREAD

**Issue by safinaskar** [bagder/http2-explained#16]
8.3 says:
"curl and libcurl has its implementation based on the separate http2 library called nghttp2 and supports plain-text http2..."

plain-text http2?! http2 is binary and it cannot be plain-text, this sentence is confusing. You mean non-TLS http2, right?

**Comment by bagder** [comment]
Modified now to better describe it as "insecure". "plain text" is rather widely used to mean non-TLS in HTTP/2 documentation but I will agree that it isn't always obvious to casual readers.

**Comment by safinaskar** [comment]
Caption of 10.2 still says "plain text". (And WYSIWYG-orientired formats such as fodt [Yes, fodt is plain text, but...] are bad for storing in git. I was not able to see fodt diff here, at Github)

**Comment by bagder** [comment]
Yes it still says that, with the addition of "insecure". This is because "plain text" is a common term used for non-TLS connections so I don't want to remove it completely. Plain text vs encrypted.

Yes, fodt is pretty crappy format to view on github. Never claimed otherwise. I've chosen to stick to it simply because I've not found a convenient alternative format that gives me the same level of freedom when writing/creating the document.

An experimental version using a more reading-friendly format as converted by @Lukasa is found here: http://http2-explained.readthedocs.org/en/latest/index.html (slightly older version of the document)

**Comment by safinaskar** [comment]
OK
