### ISSUE TITLE
Headers in wrong order

### ISSUE THREAD

**Issue by gaopinghuang0** [bagder/http2-explained#205]
The headers of the gitbook are in wrong order, as shown in the screenshot below:

![image](https://user-images.githubusercontent.com/9276774/72862875-b2c45f00-3c9c-11ea-9f58-15195c712ec8.png)

**Comment by wlonkly** [comment]
I took a look into this because it was bugging me, and it looks like the situation is this:

1. the book was written the OSS Gitbook (3.2.3), which supports multiple languages at top level and uses a `SUMMARY.md` inside each language to determine chapter order
2. it's being hosted on gitbook.com, which uses "Gitbook 4", which is a significant rewrite and which is not backwards-compatible; specifically, it no longer supports multiple languages, and it requires a `.gitbook.yaml` at root level pointing to a project-wide `SUMMARY.md`

(Re (2), see my [two-language example](https://wlonkly.gitbook.io/http2-test/v/test/) from [this branch](https://github.com/wlonkly/http2-explained/tree/test).)

So there's a few ways to fix it depending on how @bagder wants to go forward:

* commit to using Gitbook.com, update the book to Gitbook 4, and have a single `SUMMARY.md` which covers all languages, and chapters in a language are effectively subchapters of the language "chapter"
* If @bagder has a legacy.gitbook.com account, host the book as-is on that instead of on "new" gitbook.com, but that's gonna run out of time someday, and you can't sign up new accounts there now
* Continue using OSS gitbook, hosting the book somewhere other than on gitbook.com, which would probably involve build tooling.

I really appreciated having this book available and would be happy to do the work to get the formatting fixed up, once I know which direction to head in!

**Comment by bagder** [comment]
Thanks for this @wlonkly. I wish gitbooks would have been up front and clear with this when they pushed me into switching away from the legacy version into this. :frowning_face: 

I don't think going back to legacy is a way forward, and I don't think hosting it myself is the short term better answer, so let's go with option A) - fix the SUMMARY.md file to get *all* the languages into a single one! (that seems like such a stupid design decision but hey, I don't make those calls).

Your help will be much appreciated! (The same problem exists in http3 explained)

**Comment by wlonkly** [comment]
Will do -- I'll get a PR up. Once we're happy with how this one turns out, I'll take a look at http3.
