### ISSUE TITLE
Remove the old .fodt / .fodp files from the repo?

### ISSUE THREAD

**Issue by machour** [bagder/http2-explained#45]
Not sure how you would feel about that, but I'm using a slow network connection and having to download the now outdated English and French fodt files seems kind of pointless now.

Maybe the presentation fodp file could be vacuum flushed too ? Everything would anyway reside for ever in the git history.

Spanish should be kept until migration is done though.

**Comment by bagder** [comment]
They're not used anymore so they don't serve any further purpose. I just wanted to keep them there for a little while longer while we're polishing the transition and we can go back and check how it looked like before without too much troubles.

Since they were already added to the git repo once so they're still in the history, they're not really removed from the repo just from what's visible now. You need to make a shallow clone to get a much smaller repo.

I removed the presentation now, it is completely out of date anyway and I don't use that material for my current presentations. If anyone is interested in presentation material I'll store that separately somewhere else.

**Comment by bagder** [comment]
Removed now
